<?php
/**
 * Created by PhpStorm.
 * User: miloslawsky
 * Date: 05.04.17
 * Time: 15:42
 */

namespace app\components;


class Cookie extends \yii\web\Cookie {

	public $secure = false;

	public function init() {
		$this->secure = \Yii::$app->request->isSecureConnection;
		parent::init(); // TODO: Change the autogenerated stub
	}
}