	<h1>Privacy Policy</h1>
	<div class="content-wrapper">
		<p>Through the website, accessing and using the Save Life ID Applications or any other Save Life ID products and/or services which may be released from time-to-time, CommLife Solutions, Inc. (“CommLife”, “us”, “we” or “our”) may provide you with access to varied user-generated and other content and interactive and informational resources (collectively, “Services”). This Privacy Policy sets forth our policies with respect to information including personally identifiable information (“PII”) and other information that is collected from you when using the Services. This Privacy Policy is incorporated by reference in the Save Life ID Terms and Conditions, which govern you use of the Services.</p>
		<p><br>1. Information We Collect</p>
		<p>When you interact with us through the Services, we may collect PII and other information from you, as further described below:</p>
		<p>a. PII That You Provide Through the Services</p>
		<p>We collect PII from you when you voluntarily choose to provide such information such as when you contact us with inquiries, respond to one of our survey, register for access to the Services or use certain Services. Wherever we collect PII we make an effort to provide a link to this Privacy Policy. By voluntarily providing us with PII, you are consenting to our use of it in accordance with this Privacy Policy. If you provide PII through the Services, you acknowledge and agree that such PII may be transferred from your current location to our offices and servers or those of our affiliates or contractors/subcontractors located in the United States and other countries. However, we will cease using your PII once you cancel or terminate your registration for the Services.</p>
		<p>b. Other Information</p>
		<p>When you utilize the Services, we may receive certain non-personally identifiable information (“non-PII”) about your use of the Services. Such information, which may be collected passively using various technologies, or via submission of data by fitness devices you have configured to work with the Services, cannot presently be used to specifically identify you. This may include certain PII which has been aggregated and/or sufficiently anonymized so that it cannot be used to specifically identify you; restricting such use to location information, gender, age and other anonymous and/or aggregate level data. We may store such information ourselves or it may be included in databases owned and maintained by our affiliates, agents or service providers. We may use such information and pool it with other information to track, for example, the total number of visitors to the Services, the number of visitors to each page of the Services, and the domain names of our visitors’ internet service providers. It is important to note that no PII is available in this process; any PII which is used will be sufficiently anonymized so that it cannot be used to specifically identify you.</p>
		<p>In providing the Services, we may use cookies, Web beacons, persistent device identifiers (e.g., Android ID), advertising identifiers (e.g., Google’s “Advertising ID,” Apple’s “IDFA”) and other similar technologies.</p>
		<p>Cookies. A Cookie is a string of information that a website saves on a visitor’s computer or mobile device and that the visitor’s browser provides to the website operator each time the visitor returns. Our cookies help provide additional functionality to the Services and help us analyze usage of the services more accurately. For instance, our Services may set a cookie on your browser that keeps you from needing to remember and then enter a password more than once during a visit to the site.</p>
		<p>Most web browsers will include a “help” section on the toolbar where you can learn how to receive notifications when you are receiving a new cookie and how to turn cookies off. We recommend leaving your cookies on in order to take advantage of some of the exciting features of our Services.</p>
		<p>c. Aggregated and Anonymized Personal Data</p>
		<p>In an ongoing effort to better understand and serve our Services’ users, we may conduct research on our end user’s demographics, interests and behavior based on the PII and other information provided to us. This research may be complied and analyzed on an aggregate basis, and we may share this aggregated data with our affiliates, agents and business partners. This aggregate information does not identify you personally. We may also disclose aggregated user statistics in order to describe our services to current and prospective business partners, and to other third parties for other lawful purposes.</p>
		<p>2. Our Use of Your PII and other Information</p>
		<p>We will use the PII you provide in a manner that is consistent with this Privacy Policy. If you provide PII for a certain reason, we may use the PII in connection with the reason for which it was provided. For instance, if you contact us by email, we will use the PII you provide to answer your question or resolve your problem. Also, if you provide PII in order to obtain access to the Services, we will use your PII to provide access to such services and to monitor your use of such services. We may also use your PII and other non-PII collected through the Services to help us improve the content and functionality of the Services, to better understand our users and to improve the Services. We may use this information to contact you in the future to tell you about services we believe will be of interest to you. We will communicate with you through email and notices posted via the Services. These communications may include a series of welcome emails which help inform you about various features of the Services. Please be aware that you will always receive certain emails from us related to the proper functioning of your account. We may send you promotional information unless you have opted out of receiving such information. If you wish to opt-out of receiving promotional emails, please click the “unsubscribe” link at the bottom of the email.</p>
		<p>3. Our Disclosure of your PII and other information</p>
		<p>There are certain circumstances in which we may share your PII with certain third parties without further notice to you, including as set forth below:</p>
		<p>a. Business Transfers</p>
		<p>As we develop our business, we might sell or buy businesses or assets. In the event of a sale, merger, reorganization, dissolution or similar event relating to all or a portion of our business or assets, PII may be part of the transferred assets.</p>
		<p>b. Service Providers, Agents and Related Third Parties</p>
		<p>We sometimes hire other companies to perform certain business-related functions. Examples include mailing information, maintaining databases and processing payments. When we employ another company to perform a function of this nature, we may need to provide them with access to certain PII. However, we only provide them with the information that they need to perform their specific function, and these third party service providers will only use your PII to perform the services requested by us.</p>
		<p>c. Legal Requirements</p>
		<p>We may also disclose your PII if required to do so by law or in the good faith belief that such action is necessary to (i) comply with a legal obligation, (ii) protect and defend our rights or property, (iii) act in urgent circumstances to protect the personal safety of users of the Services or the public, or (iv) protect against legal liability.</p>
		<p>4. Your Choices</p>
		<p>You can use the Services without providing any PII, however, you may not be able to take advantage of certain features of the Services. When you sign up for our Services, we ask you to provide PII. If we want to use this PII in a manner different than the purpose for which it was collected, we will ask for your consent prior to doing so. If we propose to use PII for any purposes other than those described in this Privacy Policy and/or in the specific notice provided when you sign up for a certain component of our Services, we will offer you an effective way to opt out of our use of your PII for those other purposes.</p>
		<p>5. Exclusions</p>
		<p>This Privacy Policy shall not apply to any unsolicited information you provide to us. This includes, but is not limited to, information posted to any public areas of our web site, such as bulletin boards (collectively, “Public Areas”), any ideas for new products or modifications to existing services, and other unsolicited submission (collectively, “Unsolicited Information”), including all content you create on the Services which by its nature are accessible or intended to be accessible by other users of the Services.</p>
		<p>All such Unsolicited Information shall be deemed to be non-confidential and we shall be free to reproduce, use, disclose, and distribute such Unsolicited Information to others without limitation or attribution.</p>
		<p>Please note that any PII or other information you provide to be displayed in your Emergency Profile, as that term is defined in our Terms and Conditions, will be accessible for others to see and thus will not be subject to the terms of this Privacy Policy. We cannot and will not be responsible for what third parties do with any PII or other information you choose to make publicly available. As such, please consider carefully before disclosing any PII on your Emergency Profile.</p>
		<p>6. Children</p>
		<p>We do not knowingly collect PII from children under the age of majority and do not target our websites to children under the age of majority. If you are under the age of majority in your locality, please do not submit any PII through the Services. We encourage parents and legal guardians to monitor their children’s internet usage and to help enforce our Privacy Policy by instructing their children to never provide PII through any of our Services without your permission. If you have reason to believe that a child under the age of majority has provided PII to us, please contact us, and we will endeavor to delete that information from our database within a reasonable time.</p>
		<p>7. Links to other websites</p>
		<p>This Privacy Policy applies only to the Services. The Services may frame or contain references or links to other websites not operated or controlled by us (the “Third Party Services”). The policies and procedures we described here do not apply to the Third Party Services. The links from the Services do not imply our review or endorsement of the Third Party Services. For information regarding such Third Party treatment of your information, please consult their Privacy Policies, which we encourage you to do.</p>
		<p>8. Security</p>
		<p>We are concerned about safeguarding the confidentiality of your information. We provide physical, electronic, and procedural safeguards to protect information we process and maintain. For example, we limit access to this information to authorized employees and contractors who need to know that information in order to operate, develop or improve our Services. These individuals are bound by confidentiality obligations and may be subject to discipline if they fail to meet those obligations. Please be aware that, although we endeavor to provide reasonable security for information we process and maintain, no security system can prevent all potential security breaches. In particular, email sent to or from the Services may not be secure. Therefore, you should take special care in deciding what information you send to us via email. Please keep this in mind when disclosing any PII to us via the internet.</p>
		<p>9. Data Integrity</p>
		<p>We process PII only for the purposes for which it was collected and in accordance with this Privacy Policy or any applicable service-specific privacy notice. We review our data collection, storage and processing practices to ensure that we only collect, store and process PII needed to provide or improve our Services. We take reasonable steps to ensure that the PII we process is accurate, complete, and current; but we depend on our users to update or correct their PII whenever necessary.</p>
		<p>10. Enforcement</p>
		<p>We regularly review our compliance with this Privacy Policy. Please feel free to direct any questions or concerns regarding this Privacy Policy or our treatment of PII by contacting us through this website. We receive formal written complaints, it is our policy to contact the complainant regarding their concerns.</p>
		<p>11. Changes to our Privacy Policy</p>
		<p>The Services we offer may change from time to time. As a result, at times it may be necessary for us to make changes to this Privacy Policy. Accordingly, we reserve the right to update or modify this Privacy Policy at any time and from time to time without prior notice. Please review this policy periodically, and especially before you provide any PII. This Privacy Policy was last updated on the date indicated above. Your continued use of the Services after any changes or revision to this Privacy Policy shall indicate your agreement with the terms of such revised Privacy Policy.</p>
		<p>12. Access to Information</p>
		<p>We strive to keep your PII accurately recorded. Through the Services, we provide you with access to update your profile and revise you PII previously submitted to the Services.</p>
		<p>13. Contacting us</p>
		<p>If you have any additional questions or concerns about this Privacy Policy or our information practices, please feel free to contact us at any time at info@savelifeid.com.</p>
	</div>
